version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /xml/mongodb:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db